modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
issueTrackerURL="https://github.com/TelepathicGrunt/RepurposedStructures/issues" #optional
license="https://github.com/TelepathicGrunt/RepurposedStructures/blob/latest-released/LICENSE"

[[mods]] #mandatory
modId="repurposed_structures" #mandatory
logoFile="RepurposedStructuresLogo.png"
logoBlur=false
version="${file.jarVersion}" #mandatory
displayName="Repurposed Structures" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/repurposed-structures"
authors="TelepathicGrunt"
credits="Special thanks to /r/l-ll-ll-l_IsDisLoss, miguelforge, and cannon_foddr for donating some structures to this mod!"
description='''
Taking existing vanilla structures and changing them up for extra variety!
'''

[[dependencies.repurposed_structures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"

[[dependencies.repurposed_structures]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.12,)"